#  -- ID 對應表 --
SIGN_CLASSES = [
    'complementary--accident-area--g3',
    'complementary--both-directions--g1',
    'complementary--buses--g1',
    'complementary--chevron-left--g1',
    'complementary--chevron-left--g2',
    'complementary--chevron-left--g3',
    'complementary--chevron-left--g4',
    'complementary--chevron-left--g5',
    'complementary--chevron-right--g1',
    'complementary--chevron-right--g3',
    'complementary--chevron-right--g4',
    'complementary--chevron-right--g5',
    'complementary--chevron-right-unsure--g6',
    'complementary--distance--g1',
    'complementary--distance--g2',
    'complementary--distance--g3',
    'complementary--except-bicycles--g1',
    'complementary--extent-of-prohibition-area-both-direction--g1',
    'complementary--go-left--g1',
    'complementary--go-right--g1',
    'complementary--go-right--g2',
    'complementary--keep-left--g1',
    'complementary--keep-right--g1',
    'complementary--maximum-speed-limit-15--g1',
    'complementary--maximum-speed-limit-20--g1',
    'complementary--maximum-speed-limit-25--g1',
    'complementary--maximum-speed-limit-30--g1',
    'complementary--maximum-speed-limit-35--g1',
    'complementary--maximum-speed-limit-40--g1',
    'complementary--maximum-speed-limit-45--g1',
    'complementary--maximum-speed-limit-50--g1',
    'complementary--maximum-speed-limit-55--g1',
    'complementary--maximum-speed-limit-70--g1',
    'complementary--maximum-speed-limit-75--g1',
    'complementary--obstacle-delineator--g1',
    'complementary--obstacle-delineator--g2',
    'complementary--one-direction-left--g1',
    'complementary--pass-right--g1',
    'complementary--priority-route-at-intersection--g1',
    'complementary--tow-away-zone--g1',
    'complementary--trucks--g1',
    'complementary--trucks-turn-right--g1',
    'complementary--turn-left--g2',
    'complementary--turn-right--g2',
    'information--airport--g1',
    'information--airport--g2',
    'information--bike-route--g1',
    'information--camp--g1',
    'information--central-lane--g1',
    'information--children--g1',
    'information--dead-end--g1',
    'information--dead-end-except-bicycles--g1',
    'information--disabled-persons--g1',
    'information--emergency-facility--g2',
    'information--end-of-built-up-area--g1',
    'information--end-of-limited-access-road--g1',
    'information--end-of-motorway--g1',
    'information--end-of-pedestrians-only--g2',
    'information--food--g2',
    'information--gas-station--g1',
    'information--gas-station--g3',
    'information--highway-exit--g1',
    'information--highway-interstate-route--g2',
    'information--hospital--g1',
    'information--interstate-route--g1',
    'information--limited-access-road--g1',
    'information--living-street--g1',
    'information--lodging--g1',
    'information--minimum-speed-40--g1',
    'information--motorway--g1',
    'information--no-parking--g3',
    'information--parking--g1',
    'information--parking--g2',
    'information--parking--g3',
    'information--parking--g45',
    'information--parking--g5',
    'information--parking--g6',
    'information--pedestrians-crossing--g1',
    'information--pedestrians-crossing--g2',
    'information--road-bump--g1',
    'information--safety-area--g2',
    'information--stairs--g1',
    'information--telephone--g1',
    'information--telephone--g2',
    'information--trailer-camping--g1',
    'information--tram-bus-stop--g2',
    'other-sign',
    'regulatory--bicycles-only--g1',
    'regulatory--bicycles-only--g3',
    'regulatory--buses-only--g1',
    'regulatory--detour-left--g1',
    'regulatory--do-not-block-intersection--g1',
    'regulatory--do-not-stop-on-tracks--g1',
    'regulatory--dual-lanes-go-straight-on-left--g1',
    'regulatory--dual-lanes-go-straight-on-right--g1',
    'regulatory--dual-lanes-turn-left-no-u-turn--g1',
    'regulatory--dual-lanes-turn-left-or-straight--g1',
    'regulatory--dual-lanes-turn-right-or-straight--g1',
    'regulatory--dual-path-bicycles-and-pedestrians--g1',
    'regulatory--dual-path-pedestrians-and-bicycles--g1',
    'regulatory--end-of-bicycles-only--g1',
    'regulatory--end-of-buses-only--g1',
    'regulatory--end-of-maximum-speed-limit-30--g2',
    'regulatory--end-of-maximum-speed-limit-70--g1',
    'regulatory--end-of-maximum-speed-limit-70--g2',
    'regulatory--end-of-prohibition--g1',
    'regulatory--end-of-speed-limit-zone--g1',
    'regulatory--give-way-to-oncoming-traffic--g1',
    'regulatory--go-straight--g1',
    'regulatory--go-straight--g3',
    'regulatory--go-straight-or-turn-left--g1',
    'regulatory--go-straight-or-turn-left--g2',
    'regulatory--go-straight-or-turn-left--g3',
    'regulatory--go-straight-or-turn-right--g3',
    'regulatory--height-limit--g1',
    'regulatory--keep-left--g1',
    'regulatory--keep-left--g2',
    'regulatory--keep-right--g1',
    'regulatory--keep-right--g4',
    'regulatory--keep-right--g6',
    'regulatory--lane-control--g1',
    'regulatory--left-turn-yield-on-green--g1',
    'regulatory--maximum-speed-limit-10--g1',
    'regulatory--maximum-speed-limit-100--g1',
    'regulatory--maximum-speed-limit-100--g3',
    'regulatory--maximum-speed-limit-110--g1',
    'regulatory--maximum-speed-limit-120--g1',
    'regulatory--maximum-speed-limit-15--g1',
    'regulatory--maximum-speed-limit-20--g1',
    'regulatory--maximum-speed-limit-25--g1',
    'regulatory--maximum-speed-limit-25--g2',
    'regulatory--maximum-speed-limit-30--g1',
    'regulatory--maximum-speed-limit-30--g3',
    'regulatory--maximum-speed-limit-35--g2',
    'regulatory--maximum-speed-limit-40--g1',
    'regulatory--maximum-speed-limit-40--g3',
    'regulatory--maximum-speed-limit-40--g6',
    'regulatory--maximum-speed-limit-45--g1',
    'regulatory--maximum-speed-limit-45--g3',
    'regulatory--maximum-speed-limit-5--g1',
    'regulatory--maximum-speed-limit-50--g1',
    'regulatory--maximum-speed-limit-55--g2',
    'regulatory--maximum-speed-limit-60--g1',
    'regulatory--maximum-speed-limit-65--g2',
    'regulatory--maximum-speed-limit-70--g1',
    'regulatory--maximum-speed-limit-80--g1',
    'regulatory--maximum-speed-limit-90--g1',
    'regulatory--maximum-speed-limit-led-100--g1',
    'regulatory--maximum-speed-limit-led-60--g1',
    'regulatory--minimum-safe-distance--g1',
    'regulatory--no-bicycles--g1',
    'regulatory--no-bicycles--g2',
    'regulatory--no-bicycles--g3',
    'regulatory--no-buses--g3',
    'regulatory--no-entry--g1',
    'regulatory--no-hawkers--g1',
    'regulatory--no-heavy-goods-vehicles--g1',
    'regulatory--no-heavy-goods-vehicles--g2',
    'regulatory--no-heavy-goods-vehicles--g4',
    'regulatory--no-heavy-goods-vehicles--g5',
    'regulatory--no-left-turn--g1',
    'regulatory--no-left-turn--g3',
    'regulatory--no-mopeds-or-bicycles--g1',
    'regulatory--no-motor-vehicle-trailers--g1',
    'regulatory--no-motor-vehicles--g1',
    'regulatory--no-motor-vehicles--g4',
    'regulatory--no-motor-vehicles-except-motorcycles--g1',
    'regulatory--no-motor-vehicles-except-motorcycles--g2',
    'regulatory--no-motorcycles--g1',
    'regulatory--no-motorcycles--g2',
    'regulatory--no-overtaking--g1',
    'regulatory--no-overtaking--g2',
    'regulatory--no-overtaking--g4',
    'regulatory--no-overtaking--g5',
    'regulatory--no-overtaking-by-heavy-goods-vehicles--g1',
    'regulatory--no-parking--g1',
    'regulatory--no-parking--g2',
    'regulatory--no-parking--g5',
    'regulatory--no-parking-or-no-stopping--g1',
    'regulatory--no-parking-or-no-stopping--g2',
    'regulatory--no-parking-or-no-stopping--g3',
    'regulatory--no-pedestrians--g1',
    'regulatory--no-pedestrians--g2',
    'regulatory--no-pedestrians--g3',
    'regulatory--no-pedestrians-or-bicycles--g1',
    'regulatory--no-right-turn--g1',
    'regulatory--no-right-turn--g2',
    'regulatory--no-right-turn--g3',
    'regulatory--no-stopping--g15',
    'regulatory--no-stopping--g2',
    'regulatory--no-stopping--g4',
    'regulatory--no-stopping--g5',
    'regulatory--no-stopping--g8',
    'regulatory--no-straight-through--g1',
    'regulatory--no-straight-through--g2',
    'regulatory--no-turn-on-red--g1',
    'regulatory--no-turn-on-red--g2',
    'regulatory--no-turn-on-red--g3',
    'regulatory--no-turns--g1',
    'regulatory--no-u-turn--g1',
    'regulatory--no-u-turn--g2',
    'regulatory--no-u-turn--g3',
    'regulatory--no-vehicles-carrying-dangerous-goods--g1',
    'regulatory--one-way-left--g1',
    'regulatory--one-way-left--g2',
    'regulatory--one-way-left--g3',
    'regulatory--one-way-right--g1',
    'regulatory--one-way-right--g2',
    'regulatory--one-way-right--g3',
    'regulatory--one-way-straight--g1',
    'regulatory--parking-restrictions--g2',
    'regulatory--pass-on-either-side--g1',
    'regulatory--passing-lane-ahead--g1',
    'regulatory--pedestrians-only--g1',
    'regulatory--priority-over-oncoming-vehicles--g1',
    'regulatory--priority-road--g4',
    'regulatory--radar-enforced--g1',
    'regulatory--reversible-lanes--g2',
    'regulatory--road-closed--g1',
    'regulatory--road-closed--g2',
    'regulatory--road-closed-to-vehicles--g3',
    'regulatory--roundabout--g1',
    'regulatory--roundabout--g2',
    'regulatory--shared-path-bicycles-and-pedestrians--g1',
    'regulatory--shared-path-pedestrians-and-bicycles--g1',
    'regulatory--stop--g1',
    'regulatory--stop--g10',
    'regulatory--stop--g2',
    'regulatory--stop-here-on-red-or-flashing-light--g1',
    'regulatory--stop-here-on-red-or-flashing-light--g2',
    'regulatory--stop-signals--g1',
    'regulatory--text-four-lines--g1',
    'regulatory--triple-lanes-turn-left-center-lane--g1',
    'regulatory--truck-speed-limit-60--g1',
    'regulatory--turn-left--g1',
    'regulatory--turn-left--g2',
    'regulatory--turn-left--g3',
    'regulatory--turn-left-ahead--g1',
    'regulatory--turn-right--g1',
    'regulatory--turn-right--g2',
    'regulatory--turn-right--g3',
    'regulatory--turn-right-ahead--g1',
    'regulatory--turn-right-ahead--g2',
    'regulatory--turning-vehicles-yield-to-pedestrians--g1',
    'regulatory--u-turn--g1',
    'regulatory--weight-limit--g1',
    'regulatory--weight-limit-with-trucks--g1',
    'regulatory--width-limit--g1',
    'regulatory--wrong-way--g1',
    'regulatory--yield--g1',
    'warning--accidental-area-unsure--g2',
    'warning--added-lane-right--g1',
    'warning--bicycles-crossing--g1',
    'warning--bicycles-crossing--g3',
    'warning--children--g1',
    'warning--children--g2',
    'warning--crossroads--g1',
    'warning--crossroads--g3',
    'warning--crossroads-with-priority-to-the-right--g1',
    'warning--curve-left--g1',
    'warning--curve-left--g2',
    'warning--curve-right--g1',
    'warning--curve-right--g2',
    'warning--dip--g2',
    'warning--divided-highway-ends--g1',
    'warning--divided-highway-ends--g2',
    'warning--domestic-animals--g1',
    'warning--domestic-animals--g3',
    'warning--double-curve-first-left--g1',
    'warning--double-curve-first-left--g2',
    'warning--double-curve-first-right--g1',
    'warning--double-curve-first-right--g2',
    'warning--double-reverse-curve-right--g1',
    'warning--dual-lanes-right-turn-or-go-straight--g1',
    'warning--emergency-vehicles--g1',
    'warning--equestrians-crossing--g2',
    'warning--falling-rocks-or-debris-right--g1',
    'warning--falling-rocks-or-debris-right--g2',
    'warning--falling-rocks-or-debris-right--g4',
    'warning--flaggers-in-road--g1',
    'warning--hairpin-curve-left--g1',
    'warning--hairpin-curve-left--g3',
    'warning--hairpin-curve-right--g1',
    'warning--horizontal-alignment-left--g1',
    'warning--horizontal-alignment-right--g1',
    'warning--horizontal-alignment-right--g3',
    'warning--junction-with-a-side-road-acute-left--g1',
    'warning--junction-with-a-side-road-acute-right--g1',
    'warning--junction-with-a-side-road-perpendicular-left--g1',
    'warning--junction-with-a-side-road-perpendicular-left--g3',
    'warning--junction-with-a-side-road-perpendicular-left--g4',
    'warning--junction-with-a-side-road-perpendicular-right--g1',
    'warning--junction-with-a-side-road-perpendicular-right--g3',
    'warning--kangaloo-crossing--g1',
    'warning--loop-270-degree--g1',
    'warning--narrow-bridge--g1',
    'warning--narrow-bridge--g3',
    'warning--offset-roads--g3',
    'warning--other-danger--g1',
    'warning--other-danger--g3',
    'warning--pass-left-or-right--g1',
    'warning--pass-left-or-right--g2',
    'warning--pedestrian-stumble-train--g1',
    'warning--pedestrians-crossing--g1',
    'warning--pedestrians-crossing--g10',
    'warning--pedestrians-crossing--g11',
    'warning--pedestrians-crossing--g12',
    'warning--pedestrians-crossing--g4',
    'warning--pedestrians-crossing--g5',
    'warning--playground--g1',
    'warning--playground--g3',
    'warning--railroad-crossing--g1',
    'warning--railroad-crossing--g3',
    'warning--railroad-crossing--g4',
    'warning--railroad-crossing-with-barriers--g1',
    'warning--railroad-crossing-with-barriers--g4',
    'warning--railroad-crossing-without-barriers--g1',
    'warning--railroad-crossing-without-barriers--g3',
    'warning--railroad-crossing-without-barriers--g4',
    'warning--railroad-intersection--g3',
    'warning--restricted-zone--g1',
    'warning--road-bump--g1',
    'warning--road-bump--g2',
    'warning--road-narrows--g1',
    'warning--road-narrows--g2',
    'warning--road-narrows-left--g1',
    'warning--road-narrows-left--g2',
    'warning--road-narrows-right--g1',
    'warning--road-narrows-right--g2',
    'warning--road-widens--g1',
    'warning--road-widens-right--g1',
    'warning--roadworks--g1',
    'warning--roadworks--g2',
    'warning--roadworks--g3',
    'warning--roadworks--g4',
    'warning--roadworks--g6',
    'warning--roundabout--g1',
    'warning--roundabout--g25',
    'warning--school-zone--g2',
    'warning--shared-lane-motorcycles-bicycles--g1',
    'warning--slippery-road-surface--g1',
    'warning--slippery-road-surface--g2',
    'warning--steep-ascent--g7',
    'warning--stop-ahead--g9',
    'warning--t-roads--g1',
    'warning--t-roads--g2',
    'warning--texts--g1',
    'warning--texts--g2',
    'warning--texts--g3',
    'warning--traffic-merges-left--g1',
    'warning--traffic-merges-left--g2',
    'warning--traffic-merges-right--g1',
    'warning--traffic-merges-right--g2',
    'warning--traffic-signals--g1',
    'warning--traffic-signals--g2',
    'warning--traffic-signals--g4',
    'warning--trail-crossing--g2',
    'warning--trams-crossing--g1',
    'warning--trucks-crossing--g1',
    'warning--turn-left--g1',
    'warning--turn-right--g1',
    'warning--turn-right--g2',
    'warning--two-way-traffic--g1',
    'warning--two-way-traffic--g2',
    'warning--uneven-road--g2',
    'warning--uneven-road--g6',
    'warning--wild-animals--g1',
    'warning--wild-animals--g4',
    'warning--winding-road-first-left--g2',
    'warning--winding-road-first-right--g1',
    'warning--wombat-crossing--g1',
    'warning--y-roads--g1',
]


# -- 中譯字典 --
SIGN_ZH = {
    'complementary--accident-area--g3': '輔助：易肇事路段',
    'complementary--both-directions--g1': '輔助：雙向',
    'complementary--buses--g1': '輔助：公車/大客車',
    'complementary--chevron-left--g1': '輔助：左彎導引',
    'complementary--chevron-left--g2': '輔助：左彎導引',
    'complementary--chevron-left--g3': '輔助：左彎導引',
    'complementary--chevron-left--g4': '輔助：左彎導引',
    'complementary--chevron-left--g5': '輔助：左彎導引',
    'complementary--chevron-right--g1': '輔助：右彎導引',
    'complementary--chevron-right--g3': '輔助：右彎導引',
    'complementary--chevron-right--g4': '輔助：右彎導引',
    'complementary--chevron-right--g5': '輔助：右彎導引',
    'complementary--chevron-right-unsure--g6': '輔助：右彎導引(不確定)',
    'complementary--distance--g1': '輔助：距離',
    'complementary--distance--g2': '輔助：距離',
    'complementary--distance--g3': '輔助：距離',
    'complementary--except-bicycles--g1': '輔助：自行車除外',
    'complementary--extent-of-prohibition-area-both-direction--g1': '輔助：雙向禁止區域範圍',
    'complementary--go-left--g1': '輔助：靠左行駛',
    'complementary--go-right--g1': '輔助：靠右行駛',
    'complementary--go-right--g2': '輔助：靠右行駛',
    'complementary--keep-left--g1': '輔助：靠左行駛',
    'complementary--keep-right--g1': '輔助：靠右行駛',
    'complementary--maximum-speed-limit-15--g1': '輔助：最高速限 15',
    'complementary--maximum-speed-limit-20--g1': '輔助：最高速限 20',
    'complementary--maximum-speed-limit-25--g1': '輔助：最高速限 25',
    'complementary--maximum-speed-limit-30--g1': '輔助：最高速限 30',
    'complementary--maximum-speed-limit-35--g1': '輔助：最高速限 35',
    'complementary--maximum-speed-limit-40--g1': '輔助：最高速限 40',
    'complementary--maximum-speed-limit-45--g1': '輔助：最高速限 45',
    'complementary--maximum-speed-limit-50--g1': '輔助：最高速限 50',
    'complementary--maximum-speed-limit-55--g1': '輔助：最高速限 55',
    'complementary--maximum-speed-limit-70--g1': '輔助：最高速限 70',
    'complementary--maximum-speed-limit-75--g1': '輔助：最高速限 75',
    'complementary--obstacle-delineator--g1': '輔助：障礙物導標',
    'complementary--obstacle-delineator--g2': '輔助：障礙物導標',
    'complementary--one-direction-left--g1': '輔助：單向靠左',
    'complementary--pass-right--g1': '輔助：右側通行',
    'complementary--priority-route-at-intersection--g1': '輔助：路口優先路線',
    'complementary--tow-away-zone--g1': '輔助：拖吊區',
    'complementary--trucks--g1': '輔助：大貨車',
    'complementary--trucks-turn-right--g1': '輔助：大貨車右轉',
    'complementary--turn-left--g2': '輔助：左轉',
    'complementary--turn-right--g2': '輔助：右轉',

    'information--airport--g1': '指示：機場',
    'information--airport--g2': '指示：機場',
    'information--bike-route--g1': '指示：自行車道',
    'information--camp--g1': '指示：露營區',
    'information--central-lane--g1': '指示：中央車道',
    'information--children--g1': '指示：兒童',
    'information--dead-end--g1': '指示：死巷/無尾巷',
    'information--dead-end-except-bicycles--g1': '指示：死巷 (自行車除外)',
    'information--disabled-persons--g1': '指示：身心障礙者專用',
    'information--emergency-facility--g2': '指示：緊急設施',
    'information--end-of-built-up-area--g1': '指示：離開市區',
    'information--end-of-limited-access-road--g1': '指示：限制進入道路終點',
    'information--end-of-motorway--g1': '指示：高速公路終點',
    'information--end-of-pedestrians-only--g2': '指示：行人專用區終點',
    'information--food--g2': '指示：餐飲',
    'information--gas-station--g1': '指示：加油站',
    'information--gas-station--g3': '指示：加油站',
    'information--highway-exit--g1': '指示：公路出口',
    'information--highway-interstate-route--g2': '指示：州際公路路線',
    'information--hospital--g1': '指示：醫院',
    'information--interstate-route--g1': '指示：州際公路路線',
    'information--limited-access-road--g1': '指示：限制進入道路',
    'information--living-street--g1': '指示：生活街區 (行人優先)',
    'information--lodging--g1': '指示：住宿',
    'information--minimum-speed-40--g1': '指示：最低速限 40',
    'information--motorway--g1': '指示：高速公路',
    'information--no-parking--g3': '指示：禁止停車',
    'information--parking--g1': '指示：停車場',
    'information--parking--g2': '指示：停車場',
    'information--parking--g3': '指示：停車場',
    'information--parking--g45': '指示：停車場',
    'information--parking--g5': '指示：停車場',
    'information--parking--g6': '指示：停車場',
    'information--pedestrians-crossing--g1': '指示：行人穿越道',
    'information--pedestrians-crossing--g2': '指示：行人穿越道',
    'information--road-bump--g1': '指示：路面突起/減速丘',
    'information--safety-area--g2': '指示：安全區',
    'information--stairs--g1': '指示：階梯',
    'information--telephone--g1': '指示：公共電話',
    'information--telephone--g2': '指示：公共電話',
    'information--trailer-camping--g1': '指示：拖車露營區',
    'information--tram-bus-stop--g2': '指示：輕軌/公車站',

    'other-sign': '其他標誌',

    'regulatory--bicycles-only--g1': '禁制：自行車專用',
    'regulatory--bicycles-only--g3': '禁制：自行車專用',
    'regulatory--buses-only--g1': '禁制：公車專用',
    'regulatory--detour-left--g1': '禁制：左側改道',
    'regulatory--do-not-block-intersection--g1': '禁制：保持路口淨空',
    'regulatory--do-not-stop-on-tracks--g1': '禁制：鐵軌上禁止停車',
    'regulatory--dual-lanes-go-straight-on-left--g1': '禁制：雙車道左側直行',
    'regulatory--dual-lanes-go-straight-on-right--g1': '禁制：雙車道右側直行',
    'regulatory--dual-lanes-turn-left-no-u-turn--g1': '禁制：雙車道左轉禁止迴轉',
    'regulatory--dual-lanes-turn-left-or-straight--g1': '禁制：雙車道左轉或直行',
    'regulatory--dual-lanes-turn-right-or-straight--g1': '禁制：雙車道右轉或直行',
    'regulatory--dual-path-bicycles-and-pedestrians--g1': '禁制：自行車與行人共用道',
    'regulatory--dual-path-pedestrians-and-bicycles--g1': '禁制：行人與自行車共用道',
    'regulatory--end-of-bicycles-only--g1': '禁制：自行車專用道終點',
    'regulatory--end-of-buses-only--g1': '禁制：公車專用道終點',
    'regulatory--end-of-maximum-speed-limit-30--g2': '禁制：最高速限 30 終點',
    'regulatory--end-of-maximum-speed-limit-70--g1': '禁制：最高速限 70 終點',
    'regulatory--end-of-maximum-speed-limit-70--g2': '禁制：最高速限 70 終點',
    'regulatory--end-of-prohibition--g1': '禁制：限制結束',
    'regulatory--end-of-speed-limit-zone--g1': '禁制：速限區終點',
    'regulatory--give-way-to-oncoming-traffic--g1': '禁制：讓對向來車先行',
    'regulatory--go-straight--g1': '禁制：僅准直行',
    'regulatory--go-straight--g3': '禁制：僅准直行',
    'regulatory--go-straight-or-turn-left--g1': '禁制：直行或左轉',
    'regulatory--go-straight-or-turn-left--g2': '禁制：直行或左轉',
    'regulatory--go-straight-or-turn-left--g3': '禁制：直行或左轉',
    'regulatory--go-straight-or-turn-right--g3': '禁制：直行或右轉',
    'regulatory--height-limit--g1': '禁制：限高',
    'regulatory--keep-left--g1': '禁制：靠左行駛',
    'regulatory--keep-left--g2': '禁制：靠左行駛',
    'regulatory--keep-right--g1': '禁制：靠右行駛',
    'regulatory--keep-right--g4': '禁制：靠右行駛',
    'regulatory--keep-right--g6': '禁制：靠右行駛',
    'regulatory--lane-control--g1': '禁制：車道管制',
    'regulatory--left-turn-yield-on-green--g1': '禁制：綠燈左轉需讓行',
    'regulatory--maximum-speed-limit-10--g1': '禁制：最高速限 10',
    'regulatory--maximum-speed-limit-100--g1': '禁制：最高速限 100',
    'regulatory--maximum-speed-limit-100--g3': '禁制：最高速限 100',
    'regulatory--maximum-speed-limit-110--g1': '禁制：最高速限 110',
    'regulatory--maximum-speed-limit-120--g1': '禁制：最高速限 120',
    'regulatory--maximum-speed-limit-15--g1': '禁制：最高速限 15',
    'regulatory--maximum-speed-limit-20--g1': '禁制：最高速限 20',
    'regulatory--maximum-speed-limit-25--g1': '禁制：最高速限 25',
    'regulatory--maximum-speed-limit-25--g2': '禁制：最高速限 25',
    'regulatory--maximum-speed-limit-30--g1': '禁制：最高速限 30',
    'regulatory--maximum-speed-limit-30--g3': '禁制：最高速限 30',
    'regulatory--maximum-speed-limit-35--g2': '禁制：最高速限 35',
    'regulatory--maximum-speed-limit-40--g1': '禁制：最高速限 40',
    'regulatory--maximum-speed-limit-40--g3': '禁制：最高速限 40',
    'regulatory--maximum-speed-limit-40--g6': '禁制：最高速限 40',
    'regulatory--maximum-speed-limit-45--g1': '禁制：最高速限 45',
    'regulatory--maximum-speed-limit-45--g3': '禁制：最高速限 45',
    'regulatory--maximum-speed-limit-5--g1': '禁制：最高速限 5',
    'regulatory--maximum-speed-limit-50--g1': '禁制：最高速限 50',
    'regulatory--maximum-speed-limit-55--g2': '禁制：最高速限 55',
    'regulatory--maximum-speed-limit-60--g1': '禁制：最高速限 60',
    'regulatory--maximum-speed-limit-65--g2': '禁制：最高速限 65',
    'regulatory--maximum-speed-limit-70--g1': '禁制：最高速限 70',
    'regulatory--maximum-speed-limit-80--g1': '禁制：最高速限 80',
    'regulatory--maximum-speed-limit-90--g1': '禁制：最高速限 90',
    'regulatory--maximum-speed-limit-led-100--g1': '禁制：最高速限 100 (LED顯示)',
    'regulatory--maximum-speed-limit-led-60--g1': '禁制：最高速限 60 (LED顯示)',
    'regulatory--minimum-safe-distance--g1': '禁制：保持安全車距',
    'regulatory--no-bicycles--g1': '禁制：禁止自行車進入',
    'regulatory--no-bicycles--g2': '禁制：禁止自行車進入',
    'regulatory--no-bicycles--g3': '禁制：禁止自行車進入',
    'regulatory--no-buses--g3': '禁制：禁止大客車進入',
    'regulatory--no-entry--g1': '禁制：禁止進入',
    'regulatory--no-hawkers--g1': '禁制：禁止設攤',
    'regulatory--no-heavy-goods-vehicles--g1': '禁制：禁止大貨車進入',
    'regulatory--no-heavy-goods-vehicles--g2': '禁制：禁止大貨車進入',
    'regulatory--no-heavy-goods-vehicles--g4': '禁制：禁止大貨車進入',
    'regulatory--no-heavy-goods-vehicles--g5': '禁制：禁止大貨車進入',
    'regulatory--no-left-turn--g1': '禁制：禁止左轉',
    'regulatory--no-left-turn--g3': '禁制：禁止左轉',
    'regulatory--no-mopeds-or-bicycles--g1': '禁制：禁止機車與自行車進入',
    'regulatory--no-motor-vehicle-trailers--g1': '禁制：禁止拖車進入',
    'regulatory--no-motor-vehicles--g1': '禁制：禁止汽車進入',
    'regulatory--no-motor-vehicles--g4': '禁制：禁止汽車進入',
    'regulatory--no-motor-vehicles-except-motorcycles--g1': '禁制：禁止汽車進入 (機車除外)',
    'regulatory--no-motor-vehicles-except-motorcycles--g2': '禁制：禁止汽車進入 (機車除外)',
    'regulatory--no-motorcycles--g1': '禁制：禁止機車進入',
    'regulatory--no-motorcycles--g2': '禁制：禁止機車進入',
    'regulatory--no-overtaking--g1': '禁制：禁止超車',
    'regulatory--no-overtaking--g2': '禁制：禁止超車',
    'regulatory--no-overtaking--g4': '禁制：禁止超車',
    'regulatory--no-overtaking--g5': '禁制：禁止超車',
    'regulatory--no-overtaking-by-heavy-goods-vehicles--g1': '禁制：大貨車禁止超車',
    'regulatory--no-parking--g1': '禁制：禁止停車',
    'regulatory--no-parking--g2': '禁制：禁止停車',
    'regulatory--no-parking--g5': '禁制：禁止停車',
    'regulatory--no-parking-or-no-stopping--g1': '禁制：禁止臨時停車或停車',
    'regulatory--no-parking-or-no-stopping--g2': '禁制：禁止臨時停車或停車',
    'regulatory--no-parking-or-no-stopping--g3': '禁制：禁止臨時停車或停車',
    'regulatory--no-pedestrians--g1': '禁制：禁止行人通行',
    'regulatory--no-pedestrians--g2': '禁制：禁止行人通行',
    'regulatory--no-pedestrians--g3': '禁制：禁止行人通行',
    'regulatory--no-pedestrians-or-bicycles--g1': '禁制：禁止行人與自行車通行',
    'regulatory--no-right-turn--g1': '禁制：禁止右轉',
    'regulatory--no-right-turn--g2': '禁制：禁止右轉',
    'regulatory--no-right-turn--g3': '禁制：禁止右轉',
    'regulatory--no-stopping--g15': '禁制：禁止臨時停車',
    'regulatory--no-stopping--g2': '禁制：禁止臨時停車',
    'regulatory--no-stopping--g4': '禁制：禁止臨時停車',
    'regulatory--no-stopping--g5': '禁制：禁止臨時停車',
    'regulatory--no-stopping--g8': '禁制：禁止臨時停車',
    'regulatory--no-straight-through--g1': '禁制：禁止直行',
    'regulatory--no-straight-through--g2': '禁制：禁止直行',
    'regulatory--no-turn-on-red--g1': '禁制：紅燈禁止轉彎',
    'regulatory--no-turn-on-red--g2': '禁制：紅燈禁止轉彎',
    'regulatory--no-turn-on-red--g3': '禁制：紅燈禁止轉彎',
    'regulatory--no-turns--g1': '禁制：禁止轉彎',
    'regulatory--no-u-turn--g1': '禁制：禁止迴轉',
    'regulatory--no-u-turn--g2': '禁制：禁止迴轉',
    'regulatory--no-u-turn--g3': '禁制：禁止迴轉',
    'regulatory--no-vehicles-carrying-dangerous-goods--g1': '禁制：禁止載運危險物品車輛進入',
    'regulatory--one-way-left--g1': '禁制：單行道向左',
    'regulatory--one-way-left--g2': '禁制：單行道向左',
    'regulatory--one-way-left--g3': '禁制：單行道向左',
    'regulatory--one-way-right--g1': '禁制：單行道向右',
    'regulatory--one-way-right--g2': '禁制：單行道向右',
    'regulatory--one-way-right--g3': '禁制：單行道向右',
    'regulatory--one-way-straight--g1': '禁制：單行道直行',
    'regulatory--parking-restrictions--g2': '禁制：停車限制',
    'regulatory--pass-on-either-side--g1': '禁制：兩側皆可通行',
    'regulatory--passing-lane-ahead--g1': '禁制：前方超車道',
    'regulatory--pedestrians-only--g1': '禁制：行人專用',
    'regulatory--priority-over-oncoming-vehicles--g1': '禁制：本向優先通行',
    'regulatory--priority-road--g4': '禁制：優先道路',
    'regulatory--radar-enforced--g1': '禁制：雷達測速照相',
    'regulatory--reversible-lanes--g2': '禁制：調撥車道',
    'regulatory--road-closed--g1': '禁制：道路封閉',
    'regulatory--road-closed--g2': '禁制：道路封閉',
    'regulatory--road-closed-to-vehicles--g3': '禁制：車輛禁止通行',
    'regulatory--roundabout--g1': '禁制：圓環遵行方向',
    'regulatory--roundabout--g2': '禁制：圓環遵行方向',
    'regulatory--shared-path-bicycles-and-pedestrians--g1': '禁制：自行車與行人共用道',
    'regulatory--shared-path-pedestrians-and-bicycles--g1': '禁制：行人與自行車共用道',
    'regulatory--stop--g1': '禁制：停車再開',
    'regulatory--stop--g10': '禁制：停車再開',
    'regulatory--stop--g2': '禁制：停車再開',
    'regulatory--stop-here-on-red-or-flashing-light--g1': '禁制：紅燈或閃燈時在此停車',
    'regulatory--stop-here-on-red-or-flashing-light--g2': '禁制：紅燈或閃燈時在此停車',
    'regulatory--stop-signals--g1': '禁制：停車號誌',
    'regulatory--text-four-lines--g1': '禁制：文字說明(四行)',
    'regulatory--triple-lanes-turn-left-center-lane--g1': '禁制：三車道中線左轉',
    'regulatory--truck-speed-limit-60--g1': '禁制：大貨車最高速限 60',
    'regulatory--turn-left--g1': '禁制：僅准左轉',
    'regulatory--turn-left--g2': '禁制：僅准左轉',
    'regulatory--turn-left--g3': '禁制：僅准左轉',
    'regulatory--turn-left-ahead--g1': '禁制：前方左轉',
    'regulatory--turn-right--g1': '禁制：僅准右轉',
    'regulatory--turn-right--g2': '禁制：僅准右轉',
    'regulatory--turn-right--g3': '禁制：僅准右轉',
    'regulatory--turn-right-ahead--g1': '禁制：前方右轉',
    'regulatory--turn-right-ahead--g2': '禁制：前方右轉',
    'regulatory--turning-vehicles-yield-to-pedestrians--g1': '禁制：轉彎車讓行人先行',
    'regulatory--u-turn--g1': '禁制：僅准迴轉',
    'regulatory--weight-limit--g1': '禁制：限重',
    'regulatory--weight-limit-with-trucks--g1': '禁制：大貨車限重',
    'regulatory--width-limit--g1': '禁制：限寬',
    'regulatory--wrong-way--g1': '禁制：方向錯誤/禁止逆向',
    'regulatory--yield--g1': '禁制：讓路',

    'warning--accidental-area-unsure--g2': '警告：易肇事路段(不確定)',
    'warning--added-lane-right--g1': '警告：右側新增車道',
    'warning--bicycles-crossing--g1': '警告：當心自行車',
    'warning--bicycles-crossing--g3': '警告：當心自行車',
    'warning--children--g1': '警告：當心兒童',
    'warning--children--g2': '警告：當心兒童',
    'warning--crossroads--g1': '警告：十字路口',
    'warning--crossroads--g3': '警告：十字路口',
    'warning--crossroads-with-priority-to-the-right--g1': '警告：十字路口 (右方車優先)',
    'warning--curve-left--g1': '警告：左彎',
    'warning--curve-left--g2': '警告：左彎',
    'warning--curve-right--g1': '警告：右彎',
    'warning--curve-right--g2': '警告：右彎',
    'warning--dip--g2': '警告：路面凹陷',
    'warning--divided-highway-ends--g1': '警告：分隔島終點',
    'warning--divided-highway-ends--g2': '警告：分隔島終點',
    'warning--domestic-animals--g1': '警告：當心家畜',
    'warning--domestic-animals--g3': '警告：當心家畜',
    'warning--double-curve-first-left--g1': '警告：連續彎路 (先向左)',
    'warning--double-curve-first-left--g2': '警告：連續彎路 (先向左)',
    'warning--double-curve-first-right--g1': '警告：連續彎路 (先向右)',
    'warning--double-curve-first-right--g2': '警告：連續彎路 (先向右)',
    'warning--double-reverse-curve-right--g1': '警告：雙重反向彎路 (向右)',
    'warning--dual-lanes-right-turn-or-go-straight--g1': '警告：雙車道右轉或直行',
    'warning--emergency-vehicles--g1': '警告：當心救護/消防車輛',
    'warning--equestrians-crossing--g2': '警告：當心馬匹',
    'warning--falling-rocks-or-debris-right--g1': '警告：注意右側落石',
    'warning--falling-rocks-or-debris-right--g2': '警告：注意右側落石',
    'warning--falling-rocks-or-debris-right--g4': '警告：注意右側落石',
    'warning--flaggers-in-road--g1': '警告：前方有交通指揮人員',
    'warning--hairpin-curve-left--g1': '警告：左側髮夾彎',
    'warning--hairpin-curve-left--g3': '警告：左側髮夾彎',
    'warning--hairpin-curve-right--g1': '警告：右側髮夾彎',
    'warning--horizontal-alignment-left--g1': '警告：左方線形改變',
    'warning--horizontal-alignment-right--g1': '警告：右方線形改變',
    'warning--horizontal-alignment-right--g3': '警告：右方線形改變',
    'warning--junction-with-a-side-road-acute-left--g1': '警告：左側銳角岔路',
    'warning--junction-with-a-side-road-acute-right--g1': '警告：右側銳角岔路',
    'warning--junction-with-a-side-road-perpendicular-left--g1': '警告：左側直角岔路',
    'warning--junction-with-a-side-road-perpendicular-left--g3': '警告：左側直角岔路',
    'warning--junction-with-a-side-road-perpendicular-left--g4': '警告：左側直角岔路',
    'warning--junction-with-a-side-road-perpendicular-right--g1': '警告：右側直角岔路',
    'warning--junction-with-a-side-road-perpendicular-right--g3': '警告：右側直角岔路',
    'warning--kangaloo-crossing--g1': '警告：當心袋鼠',
    'warning--loop-270-degree--g1': '警告：270度環狀彎道',
    'warning--narrow-bridge--g1': '警告：狹橋',
    'warning--narrow-bridge--g3': '警告：狹橋',
    'warning--offset-roads--g3': '警告：錯位岔路',
    'warning--other-danger--g1': '警告：其他危險',
    'warning--other-danger--g3': '警告：其他危險',
    'warning--pass-left-or-right--g1': '警告：左右皆可通行',
    'warning--pass-left-or-right--g2': '警告：左右皆可通行',
    'warning--pedestrian-stumble-train--g1': '警告：小心輕軌/火車與行人',
    'warning--pedestrians-crossing--g1': '警告：當心行人',
    'warning--pedestrians-crossing--g10': '警告：當心行人',
    'warning--pedestrians-crossing--g11': '警告：當心行人',
    'warning--pedestrians-crossing--g12': '警告：當心行人',
    'warning--pedestrians-crossing--g4': '警告：當心行人',
    'warning--pedestrians-crossing--g5': '警告：當心行人',
    'warning--playground--g1': '警告：遊樂場',
    'warning--playground--g3': '警告：遊樂場',
    'warning--railroad-crossing--g1': '警告：鐵路平交道',
    'warning--railroad-crossing--g3': '警告：鐵路平交道',
    'warning--railroad-crossing--g4': '警告：鐵路平交道',
    'warning--railroad-crossing-with-barriers--g1': '警告：有柵門鐵路平交道',
    'warning--railroad-crossing-with-barriers--g4': '警告：有柵門鐵路平交道',
    'warning--railroad-crossing-without-barriers--g1': '警告：無柵門鐵路平交道',
    'warning--railroad-crossing-without-barriers--g3': '警告：無柵門鐵路平交道',
    'warning--railroad-crossing-without-barriers--g4': '警告：無柵門鐵路平交道',
    'warning--railroad-intersection--g3': '警告：鐵路交叉口',
    'warning--restricted-zone--g1': '警告：限制區域',
    'warning--road-bump--g1': '警告：路面突起',
    'warning--road-bump--g2': '警告：路面突起',
    'warning--road-narrows--g1': '警告：狹路',
    'warning--road-narrows--g2': '警告：狹路',
    'warning--road-narrows-left--g1': '警告：左側縮減',
    'warning--road-narrows-left--g2': '警告：左側縮減',
    'warning--road-narrows-right--g1': '警告：右側縮減',
    'warning--road-narrows-right--g2': '警告：右側縮減',
    'warning--road-widens--g1': '警告：道路變寬',
    'warning--road-widens-right--g1': '警告：右側道路變寬',
    'warning--roadworks--g1': '警告：前方施工',
    'warning--roadworks--g2': '警告：前方施工',
    'warning--roadworks--g3': '警告：前方施工',
    'warning--roadworks--g4': '警告：前方施工',
    'warning--roadworks--g6': '警告：前方施工',
    'warning--roundabout--g1': '警告：圓環',
    'warning--roundabout--g25': '警告：圓環',
    'warning--school-zone--g2': '警告：當心學童 (學校區域)',
    'warning--shared-lane-motorcycles-bicycles--g1': '警告：機車與自行車共用車道',
    'warning--slippery-road-surface--g1': '警告：路滑',
    'warning--slippery-road-surface--g2': '警告：路滑',
    'warning--steep-ascent--g7': '警告：險坡 (上坡)',
    'warning--stop-ahead--g9': '警告：前方停車再開',
    'warning--t-roads--g1': '警告：T型岔路',
    'warning--t-roads--g2': '警告：T型岔路',
    'warning--texts--g1': '警告：文字說明',
    'warning--texts--g2': '警告：文字說明',
    'warning--texts--g3': '警告：文字說明',
    'warning--traffic-merges-left--g1': '警告：左側車流匯入',
    'warning--traffic-merges-left--g2': '警告：左側車流匯入',
    'warning--traffic-merges-right--g1': '警告：右側車流匯入',
    'warning--traffic-merges-right--g2': '警告：右側車流匯入',
    'warning--traffic-signals--g1': '警告：注意號誌',
    'warning--traffic-signals--g2': '警告：注意號誌',
    'warning--traffic-signals--g4': '警告：注意號誌',
    'warning--trail-crossing--g2': '警告：步道交會',
    'warning--trams-crossing--g1': '警告：當心輕軌/路面電車',
    'warning--trucks-crossing--g1': '警告：當心大貨車',
    'warning--turn-left--g1': '警告：左轉彎',
    'warning--turn-right--g1': '警告：右轉彎',
    'warning--turn-right--g2': '警告：右轉彎',
    'warning--two-way-traffic--g1': '警告：雙向通行',
    'warning--two-way-traffic--g2': '警告：雙向通行',
    'warning--uneven-road--g2': '警告：路面不平',
    'warning--uneven-road--g6': '警告：路面不平',
    'warning--wild-animals--g1': '警告：當心野生動物',
    'warning--wild-animals--g4': '警告：當心野生動物',
    'warning--winding-road-first-left--g2': '警告：連續彎路 (先向左)',
    'warning--winding-road-first-right--g1': '警告：連續彎路 (先向右)',
    'warning--wombat-crossing--g1': '警告：當心袋熊',
    'warning--y-roads--g1': '警告：Y型岔路'
}